# Generated by Django 3.1.3 on 2020-12-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30, unique=True)),
                ('c_id', models.CharField(max_length=30)),
                ('m_id', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='m_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='o_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
