# Generated by Django 3.1.3 on 2020-12-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20201213_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='o_id',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='order_id',
            new_name='o_id',
        ),
    ]
