# Generated by Django 3.1.3 on 2020-12-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20201213_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='o_id',
            field=models.CharField(max_length=30),
        ),
    ]
