# Generated by Django 3.1.3 on 2020-12-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20201213_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='type_ins',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='ins_no',
            field=models.IntegerField(),
        ),
    ]
