# Generated by Django 3.1.3 on 2020-12-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20201215_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='o_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
