# Generated by Django 3.0.5 on 2020-12-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_auto_20201229_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='m_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='c_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='c_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='m_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='c_id',
            field=models.CharField(max_length=30),
        ),
    ]
