# Generated by Django 3.0.5 on 2021-01-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_auto_20210110_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='o_id',
            field=models.CharField(max_length=30),
        ),
    ]
