# Generated by Django 3.0.5 on 2021-02-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_auto_20210110_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phn_no',
            field=models.BigIntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='percent',
            field=models.IntegerField(max_length=3),
        ),
    ]
